import {
  FlatUser,
  MaintenanceBill,
  DocumentItem,
  SocietyRule,
  Notice,
  MeetingRecord,
  SponsorshipCampaign,
  DocumentRequest,
  ComplaintTicket,
  FacilityBooking,
  Notification,
  PropertyType,
  FlatPropertyTax,
} from "../types";
import { DEFAULT_UNAVAILABLE_DOC_MESSAGE } from "./constants";

// 5 Residents across Building A, B, C + Admin
export const INITIAL_FLATS: FlatUser[] = [
  // Admin
  {
    id: "flat-admin",
    flatNumber: "MC-Office",
    wing: "Society Office",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Managing Committee (Secretary - Rajesh Shetty)",
    email: "committee@emeraldheights.org",
    phone: "+91 22 2640 9988",
    role: "admin",
    isOwner: true,
    possessionDate: "01 Jan 2015",
    parkingSlot: "Admin Reserved (P-01)",
    pin: "1234",
  },

  // Building A
  {
    id: "flat-a101",
    flatNumber: "A-101",
    wing: "Building A",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Pooja Sharma",
    email: "pooja.sharma@outlook.com",
    phone: "+91 98450 11223",
    role: "resident",
    isOwner: true,
    possessionDate: "05 Jan 2019",
    parkingSlot: "P-04 (Covered Ground)",
    pin: "1234",
  },

  // Building B
  {
    id: "flat-b402",
    flatNumber: "B-402",
    wing: "Building B",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Rajesh Shetty",
    email: "rajesh.shetty@emeraldheights.org",
    phone: "+91 98200 44201",
    role: "resident",
    isOwner: true,
    possessionDate: "10 Mar 2018",
    parkingSlot: "P-42 (Covered Ground)",
    pin: "1234",
  },
  {
    id: "flat-b204",
    flatNumber: "B-204",
    wing: "Building B",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Ananya Iyer",
    email: "ananya.iyer@fintech.in",
    phone: "+91 98208 22208",
    role: "resident",
    isOwner: true,
    possessionDate: "01 Dec 2018",
    parkingSlot: "P-49 (Basement 2)",
    pin: "1234",
  },

  // Building C
  {
    id: "flat-c303",
    flatNumber: "C-303",
    wing: "Building C",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Vikram Malhotra",
    email: "vikram.m@investments.in",
    phone: "+91 98210 33311",
    role: "resident",
    isOwner: true,
    possessionDate: "01 Nov 2020",
    parkingSlot: "P-70 (Basement 2)",
    pin: "1234",
  },
  {
    id: "flat-c102",
    flatNumber: "C-102",
    wing: "Building C",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Sunita Deshmukh",
    email: "sunita.deshmukh@gmail.com",
    phone: "+91 98190 77654",
    role: "resident",
    isOwner: true,
    possessionDate: "15 Jul 2021",
    parkingSlot: "P-58 (Basement 1)",
    pin: "1234",
  },
];

export const PROPERTY_TAX_CONFIG: Record<
  PropertyType,
  { label: string; sqft: number; annualAmount: number; monthlyAmount: number }
> = {
  "1_bhk": {
    label: "1 BHK Compact (620 sq.ft)",
    sqft: 620,
    annualAmount: 10800,
    monthlyAmount: 900,
  },
  "2_bhk": {
    label: "2 BHK Standard (950 sq.ft)",
    sqft: 950,
    annualAmount: 16800,
    monthlyAmount: 1400,
  },
  "3_bhk": {
    label: "3 BHK Luxury (1,380 sq.ft)",
    sqft: 1380,
    annualAmount: 24000,
    monthlyAmount: 2000,
  },
  penthouse: {
    label: "4 BHK Penthouse (2,200 sq.ft)",
    sqft: 2200,
    annualAmount: 32400,
    monthlyAmount: 2700,
  },
};

// All 5 resident flats set to unpaid (not_paid) for live demonstration
export const INITIAL_PROPERTY_TAXES: FlatPropertyTax[] = [
  {
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    propertyType: "2_bhk",
    annualTaxAmount: 16800,
    sacNumber: "MH–MUM–2026–A101–99",
    status: "not_paid",
  },
  {
    flatId: "flat-b402",
    flatNumber: "B-402",
    residentName: "Rajesh Shetty",
    propertyType: "2_bhk",
    annualTaxAmount: 16800,
    sacNumber: "MH–MUM–2026–B402–99",
    status: "not_paid",
  },
  {
    flatId: "flat-b204",
    flatNumber: "B-204",
    residentName: "Ananya Iyer",
    propertyType: "1_bhk",
    annualTaxAmount: 10800,
    sacNumber: "MH–MUM–2026–B204–99",
    status: "not_paid",
  },
  {
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    propertyType: "3_bhk",
    annualTaxAmount: 24000,
    sacNumber: "MH–MUM–2026–C303–99",
    status: "not_paid",
  },
  {
    flatId: "flat-c102",
    flatNumber: "C-102",
    residentName: "Sunita Deshmukh",
    propertyType: "2_bhk",
    annualTaxAmount: 16800,
    sacNumber: "MH–MUM–2026–C102–99",
    status: "not_paid",
  },
];

// Current bills set to unpaid (pending) for all 5 residents
export const INITIAL_BILLS: MaintenanceBill[] = [
  // Flat A-101 (Pooja Sharma)
  {
    id: "bill-2026-10-a101",
    flatId: "flat-a101",
    flatNumber: "A-101",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-04)", amount: 500, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 1400, category: "property_tax" },
    ],
    totalAmount: 6200,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 1400,
  },
  {
    id: "bill-2026-09-a101",
    flatId: "flat-a101",
    flatNumber: "A-101",
    monthYear: "September 2026",
    billingDate: "01 Sep 2026",
    dueDate: "15 Sep 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-04)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "paid",
    isPropertyTaxIncluded: false,
    propertyTaxAmount: 0,
    paidAt: "08 Sep 2026",
    paymentRef: "RZP_202609088491",
    paymentMethod: "Razorpay",
  },

  // Flat B-402 (Rajesh Shetty)
  {
    id: "bill-2026-10-b402",
    flatId: "flat-b402",
    flatNumber: "B-402",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-42)", amount: 500, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 1400, category: "property_tax" },
    ],
    totalAmount: 6200,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 1400,
  },
  {
    id: "bill-2026-09-b402",
    flatId: "flat-b402",
    flatNumber: "B-402",
    monthYear: "September 2026",
    billingDate: "01 Sep 2026",
    dueDate: "15 Sep 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-42)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "paid",
    isPropertyTaxIncluded: false,
    propertyTaxAmount: 0,
    paidAt: "10 Sep 2026",
    paymentRef: "RZP_202609104812",
    paymentMethod: "UPI",
  },

  // Flat B-204 (Ananya Iyer)
  {
    id: "bill-2026-10-b204",
    flatId: "flat-b204",
    flatNumber: "B-204",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 2600, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 500, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 400, category: "water" },
      { id: "i4", name: "Basement 2 Parking (P-49)", amount: 400, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 900, category: "property_tax" },
    ],
    totalAmount: 4800,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 900,
  },

  // Flat C-303 (Vikram Malhotra)
  {
    id: "bill-2026-10-c303",
    flatId: "flat-c303",
    flatNumber: "C-303",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 4200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 800, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 550, category: "water" },
      { id: "i4", name: "Basement 2 Parking (P-70)", amount: 400, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 2000, category: "property_tax" },
    ],
    totalAmount: 7950,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 2000,
  },

  // Flat C-102 (Sunita Deshmukh)
  {
    id: "bill-2026-10-c102",
    flatId: "flat-c102",
    flatNumber: "C-102",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Basement 1 Parking (P-58)", amount: 450, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 1400, category: "property_tax" },
    ],
    totalAmount: 6150,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 1400,
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-1",
    flatId: "flat-a101",
    title: "Registered Agreement for Sale & Index II (Flat A-101)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_a101.pdf",
    fileSize: "4.8 MB",
    fileType: "pdf",
    uploadedAt: "12 Jan 2019",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-2",
    flatId: "flat-a101",
    title: "Society Share Certificate (Certificate No. 104)",
    category: "share_certificate",
    fileUrl: "https://example.com/docs/share_cert_a101.pdf",
    fileSize: "1.6 MB",
    fileType: "pdf",
    uploadedAt: "05 Mar 2019",
    uploadedBy: "Secretary (Admin)",
  },
  {
    id: "doc-3",
    flatId: "flat-b402",
    title: "Registered Agreement for Sale & Allotment Letter (Flat B-402)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_b402.pdf",
    fileSize: "5.1 MB",
    fileType: "pdf",
    uploadedAt: "15 Mar 2018",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-4",
    flatId: "flat-b204",
    title: "Registered Agreement for Sale & Possession Letter (Flat B-204)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_b204.pdf",
    fileSize: "4.2 MB",
    fileType: "pdf",
    uploadedAt: "02 Dec 2018",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-5",
    flatId: "flat-c303",
    title: "Registered Agreement for Sale & Stamp Duty Receipt (Flat C-303)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_c303.pdf",
    fileSize: "4.9 MB",
    fileType: "pdf",
    uploadedAt: "05 Nov 2020",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-6",
    isSocietyWide: true,
    title: "Emerald Heights CHS Model Bye-Laws (Maharashtra Co-op Societies Act)",
    category: "bylaws",
    fileUrl: "https://example.com/docs/society_byelaws_2023.pdf",
    fileSize: "8.4 MB",
    fileType: "pdf",
    uploadedAt: "01 Jan 2023",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-7",
    isSocietyWide: true,
    title: "Annual Fire Safety & Lift Audit Certificate (Form B 2026)",
    category: "insurance",
    fileUrl: "https://example.com/docs/fire_safety_audit_2026.pdf",
    fileSize: "2.1 MB",
    fileType: "pdf",
    uploadedAt: "18 Jun 2026",
    uploadedBy: "MC Facilities Head",
  },
];

export const INITIAL_RULES: SocietyRule[] = [
  {
    id: "rule-1",
    title: "Visitor & EV Vehicle Parking Regulations",
    category: "parking",
    description: "Visitors are permitted to park in designated yellow-bay visitor slots for a maximum of 6 consecutive hours. Overnight visitor parking requires prior security intimation via SMS/app. EV charging at designated slots must be freed within 30 minutes of 100% charge completion.",
    penaltyInfo: "₹500 wheel-clamp fee for unauthorized parking in private resident slots.",
    originMeeting: "AGM 2024 (Minute 7.2 - 14 Aug 2024)",
    effectiveDate: "01 Sep 2024",
    lastUpdated: "12 Mar 2025",
    version: 2,
  },
  {
    id: "rule-2",
    title: "Flat Interior Renovation & Drilling Hours",
    category: "renovation",
    description: "Civil work, heavy carpentry, and power drilling are strictly restricted to 10:00 AM – 1:00 PM and 3:00 PM – 6:00 PM on Mondays through Saturdays. No loud work is allowed on Sundays or declared public holidays. Debris must be cleared via service elevator only.",
    penaltyInfo: "₹2,000 fine on owner + immediate cessation of contractor entry.",
    originMeeting: "EGM on Resident Harmony (18 Nov 2023)",
    effectiveDate: "01 Dec 2023",
    lastUpdated: "01 Dec 2023",
    version: 1,
  },
  {
    id: "rule-3",
    title: "Pet Care & Leash Mandate in Common Areas",
    category: "pets",
    description: "All companion dogs must be on a leash when traversing corridors, lobbies, and elevators. Pet owners must utilize Elevator #2 (service lift) during peak morning rush (8:00 AM – 9:30 AM). Owners are legally responsible for scooping waste on society lawns/jogging tracks.",
    penaltyInfo: "₹1,000 fine for repeated littering in common areas.",
    originMeeting: "AGM 2023 (Minute 4.1 - 20 Aug 2023)",
    effectiveDate: "01 Sep 2023",
    lastUpdated: "15 Apr 2024",
    version: 3,
  },
  {
    id: "rule-4",
    title: "Quiet Hours & Terrace Party Guidelines",
    category: "noise",
    description: "Strict quiet hours apply across all wings between 10:30 PM and 7:00 AM. Terrace bookings for private gatherings are allowed up to 10:00 PM with zero amplified sound after 10:00 PM as per municipal noise pollution norms. Max 40 guests allowed per booking.",
    penaltyInfo: "Forfeiture of ₹5,000 security deposit for noise violations after 10:30 PM.",
    originMeeting: "EGM (09 Feb 2024)",
    effectiveDate: "01 Mar 2024",
    lastUpdated: "01 Mar 2024",
    version: 1,
  },
  {
    id: "rule-5",
    title: "Mandatory 3-Way Waste Segregation",
    category: "waste_management",
    description: "Household waste must be handed to housekeeping staff strictly segregated into Green (Wet/Biodegradable), Blue (Dry/Recyclable), and Red (Hazardous/Sanitary) bins at doorstep collection between 7:30 AM and 9:00 AM. Unsegregated bags will not be picked up.",
    penaltyInfo: "₹250 refusal notice per occurrence.",
    originMeeting: "Swachh Society Drive Resolution (10 Jan 2025)",
    effectiveDate: "01 Feb 2025",
    lastUpdated: "01 Feb 2025",
    version: 1,
  },
  {
    id: "rule-6",
    title: "Clubhouse Gymnasium & Swimming Pool Etiquette",
    category: "clubhouse",
    description: "Gymnasium is open 6:00 AM – 11:00 AM and 5:00 PM – 10:00 PM. Appropriate sportswear and clean footwear mandatory. Swimming pool requires nylon swimwear and mandatory pre-shower. Children under 12 must be accompanied by an adult.",
    originMeeting: "AGM 2022 (07 Aug 2022)",
    effectiveDate: "15 Aug 2022",
    lastUpdated: "10 Jun 2025",
    version: 2,
  },
];

// 3 Realistic Notices: 1 Urgent (Water), 1 General, 1 Maintenance
export const INITIAL_NOTICES: Notice[] = [
  {
    id: "notice-1",
    title: "Overhead Water Tank Cleaning & Supply Interruption (Tomorrow)",
    content: "Please be informed that semi-annual cleaning and sanitization of the overhead water tanks for Wings A, B, and C will take place tomorrow, Thursday, from 10:00 AM to 02:00 PM. Water supply will be suspended during this window. Residents are kindly advised to store adequate water for morning/afternoon usage.",
    body: "Please be informed that semi-annual cleaning and sanitization of the overhead water tanks for Wings A, B, and C will take place tomorrow, Thursday, from 10:00 AM to 02:00 PM. Water supply will be suspended during this window. Residents are kindly advised to store adequate water for morning/afternoon usage.",
    category: "urgent",
    postedAt: "02 Oct 2026, 06:15 PM",
    postedBy: "Facilities & Maintenance Sub-Committee",
    isPinned: true,
    translations: {
      hi: {
        title: "पानी की आपूर्ति में रुकावट — कल",
        content: "टैंक की निर्धारित सफाई और रखरखाव के लिए कल सुबह 10:00 बजे से दोपहर 2:00 बजे तक पानी की आपूर्ति बाधित रहेगी। कृपया पहले से पानी जमा कर लें। असुविधा के लिए हमें खेद है।",
        body: "टैंक की निर्धारित सफाई और रखरखाव के लिए कल सुबह 10:00 बजे से दोपहर 2:00 बजे तक पानी की आपूर्ति बाधित रहेगी। कृपया पहले से पानी जमा कर लें। असुविधा के लिए हमें खेद है।",
      },
      mr: {
        title: "पाणी पुरवठा खंडित — उद्या",
        content: "टाकीची नियोजित स्वच्छता आणि देखभालीसाठी उद्या सकाळी १०:०० ते दुपारी २:०० वाजेपर्यंत पाणीपुरवठा बंद राहील. कृपया पाण्याचा साठा अगोदर करून ठेवा. गैरसोयीबद्दल आम्ही दिलगीर आहोत.",
        body: "टाकीची नियोजित स्वच्छता आणि देखभालीसाठी उद्या सकाळी १०:०० ते दुपारी २:०० वाजेपर्यंत पाणीपुरवठा बंद राहील. कृपया पाण्याचा साठा अगोदर करून ठेवा. गैरसोयीबद्दल आम्ही दिलगीर आहोत.",
      },
      gu: {
        title: "પાણી પુરવઠો બંધ રહેશે — આવતીકાલે",
        content: "ટાંકીની નિયમિત સફાઈ અને સમારકામ માટે આવતીકાલે સવારે ૧૦:૦૦ થી બપોરે ૨:૦૦ વાગ્યા સુધી પાણી પુરવઠો બંધ રહેશે. કૃપા કરીને અગાઉથી પાણીનો સંગ્રહ કરી લો. અગવડતા બદલ અમે દિલગીર છીએ.",
        body: "ટાંકીની નિયમિત સફાઈ અને સમારકામ માટે આવતીકાલે સવારે ૧૦:૦૦ થી બપોરે ૨:૦૦ વાગ્યા સુધી પાણી પુરવઠો બંધ રહેશે. કૃપા કરીને અગાઉથી પાણીનો સંગ્રહ કરી લો. અગવડતા બદલ અમે દિલગીર છીએ.",
      },
    },
  },
  {
    id: "notice-2",
    title: "Festive Season Security & Courier Parcel Locker Guidelines",
    content: "With the festive parcel surge, all courier deliveries will be held at the Smart Delivery Kiosk located near the main security gate. Guards will scan packages and residents will receive an OTP for instant self-pickup. Valuables/food deliveries may still proceed directly to flat doors.",
    body: "With the festive parcel surge, all courier deliveries will be held at the Smart Delivery Kiosk located near the main security gate. Guards will scan packages and residents will receive an OTP for instant self-pickup. Valuables/food deliveries may still proceed directly to flat doors.",
    category: "general",
    postedAt: "20 Sep 2026, 04:30 PM",
    postedBy: "Security Sub-Committee",
    isPinned: false,
    translations: {
      hi: {
        title: "त्योहारी सीजन सुरक्षा एवं कूरियर पार्सल लॉकर दिशानिर्देश",
        content: "त्योहारी मौसम में पार्सल की अधिक संख्या को देखते हुए सभी कूरियर डिलीवरी मुख्य सुरक्षा गेट के पास स्थित स्मार्ट डिलीवरी कियोस्क पर रखी जाएंगी। गार्ड पैकेज स्कैन करेंगे और सदस्यों को स्वयं पिकअप के लिए ओटीपी मिलेगा। मूल्यवान वस्तुएं और भोजन डिलीवरी सीधे फ्लैट के दरवाजे तक आ सकती हैं।",
        body: "त्योहारी मौसम में पार्सल की अधिक संख्या को देखते हुए सभी कूरियर डिलीवरी मुख्य सुरक्षा गेट के पास स्थित स्मार्ट डिलीवरी कियोस्क पर रखी जाएंगी। गार्ड पैकेज स्कैन करेंगे और सदस्यों को स्वयं पिकअप के लिए ओटीपी मिलेगा। मूल्यवान वस्तुएं और भोजन डिलीवरी सीधे फ्लैट के दरवाजे तक आ सकती हैं।",
      },
      mr: {
        title: "सणासुदीच्या काळातील सुरक्षा आणि कुरिअर पार्सल नियमावली",
        content: "सणासुदीच्या काळात वाढत्या पार्सल डिलिव्हरीच्या पार्श्वभूमीवर सर्व कुरिअर पार्सल मुख्य प्रवेशद्वाराजवळील स्मार्ट डिलिव्हरी कियोस्कवर ठेवले जातील. सुरक्षा रक्षक पॅकेट स्कॅन करतील आणि सदस्यांना ओटीपी पाठवला जाईल. जेवणाची आणि मौल्यवान डिलिव्हरी थेट फ्लॅटपर्यंत जाऊ शकते.",
        body: "सणासुदीच्या काळात वाढत्या पार्सल डिलिव्हरीच्या पार्श्वभूमीवर सर्व कुरिअर पार्सल मुख्य प्रवेशद्वाराजवळील स्मार्ट डिलिव्हरी कियोस्कवर ठेवले जातील. सुरक्षा रक्षक पॅकेट स्कॅन करतील आणि सदस्यांना ओटीपी पाठवला जाईल. जेवणाची आणि मौल्यवान डिलिव्हरी थेट फ्लॅटपर्यंत जाऊ शकते.",
      },
      gu: {
        title: "તહેવારોની સિઝનમાં સુરક્ષા અને કુરિયર પાર્સલ લોકર માર્ગદર્શિકા",
        content: "તહેવારોની સિઝનમાં પાર્સલના ધસારાને ધ્યાનમાં રાખીને, તમામ કુરિયર ડિલિવરી મુખ્ય સુરક્ષા ગેટ પાસેના સ્માર્ટ ડિલિવરી કિઓસ્ક પર રાખવામાં આવશે. ગાર્ડ પેકેજ સ્કેન કરશે અને સભ્યોને સેલ્ફ-પિકઅપ માટે ઓટીપી પ્રાપ્ત થશે. કિંમતી સામાન અને ફૂડ ડિલિવરી સીધા ફ્લેટના દરવાજા સુધી જઈ શકે છે.",
        body: "તહેવારોની સિઝનમાં પાર્સલના ધસારાને ધ્યાનમાં રાખીને, તમામ કુરિયર ડિલિવરી મુખ્ય સુરક્ષા ગેટ પાસેના સ્માર્ટ ડિલિવરી કિઓસ્ક પર રાખવામાં આવશે. ગાર્ડ પેકેજ સ્કેન કરશે અને સભ્યોને સેલ્ફ-પિકઅપ માટે ઓટીપી પ્રાપ્ત થશે. કિંમતી સામાન અને ફૂડ ડિલિવરી સીધા ફ્લેટના દરવાજા સુધી જઈ શકે છે.",
      },
    },
  },
  {
    id: "notice-3",
    title: "Rooftop Solar Grid Net-Metering Commissioning Completed",
    content: "The Managing Committee is delighted to share that the 45kW rooftop solar photovoltaic system has received final grid synchronization approval from Tata Power / MSEDCL. Common area lighting and elevator power will now run 65% on renewable solar energy, resulting in projected monthly savings of ₹42,000 on common electricity bills.",
    body: "The Managing Committee is delighted to share that the 45kW rooftop solar photovoltaic system has received final grid synchronization approval from Tata Power / MSEDCL. Common area lighting and elevator power will now run 65% on renewable solar energy, resulting in projected monthly savings of ₹42,000 on common electricity bills.",
    category: "maintenance",
    postedAt: "28 Sep 2026, 11:00 AM",
    postedBy: "Managing Committee",
    isPinned: false,
    translations: {
      hi: {
        title: "रूफटॉप सोलर ग्रिड कमीशनिंग सफलतापूर्वक संपन्न",
        content: "प्रबंध समिति को यह बताते हुए हर्ष हो रहा है कि हमारे 45kW रूफटॉप सोलर सिस्टम को ग्रिड से जोड़ दिया गया है। कॉमन एरिया की लाइटिंग और लिफ्ट अब 65% सौर ऊर्जा से संचालित होंगी, जिससे सोसाइटी के बिजली बिल में प्रतिमाह लगभग ₹42,000 की बचत होगी।",
        body: "प्रबंध समिति को यह बताते हुए हर्ष हो रहा है कि हमारे 45kW रूफटॉप सोलर सिस्टम को ग्रिड से जोड़ दिया गया है। कॉमन एरिया की लाइटिंग और लिफ्ट अब 65% सौर ऊर्जा से संचालित होंगी, जिससे सोसाइटी के बिजली बिल में प्रतिमाह लगभग ₹42,000 की बचत होगी।",
      },
      mr: {
        title: "छतावरील सोलर ग्रीडचे काम पूर्ण झाले",
        content: "व्यवस्थापन समितीला हे सांगताना आनंद होत आहे की ४५ किलोवॅट क्षमतेच्या सोलर पॅनेल प्रणालीला मंजुरी मिळाली आहे. सामान्य भागातील दिवे आणि लिफ्ट आता सौर ऊर्जेवर चालतील, ज्यामुळे दरमहा साधारण ₹४२,००० विजेच्या बिलात बचत होईल.",
        body: "व्यवस्थापन समितीला हे सांगताना आनंद होत आहे की ४५ किलोवॅट क्षमतेच्या सोलर पॅनेल प्रणालीला मंजुरी मिळाली आहे. सामान्य भागातील दिवे आणि लिफ्ट आता सौर ऊर्जेवर चालतील, ज्यामुळे दरमहा साधारण ₹४२,००० विजेच्या बिलात बचत होईल.",
      },
      gu: {
        title: "રૂફટોપ સોલર ગ્રીડ કમિશનિંગ સફળતાપૂર્વક પૂર્ણ થયું",
        content: "મેનેજિંગ કમિટી જણાવતા ખુશી અનુભવે છે કે આપણી 45kW રૂફટોપ સોલાર સિસ્ટમને ટાટા પાવર / MSEDCL દ્વારા અંતિમ મંજૂરી મળી ગઈ છે. કોમન એરિયા લાઇટિંગ અને લિફ્ટ હવે 65% સૌર ઊર્જા પર ચાલશે, જેનાથી સોસાયટીના વીજળી બિલમાં દર મહિને આશરે ₹42,000 ની બચત થશે.",
        body: "મેનેજિંગ કમિટી જણાવતા ખુશી અનુભવે છે કે આપણી 45kW રૂફટોપ સોલાર સિસ્ટમને ટાટા પાવર / MSEDCL દ્વારા અંતિમ મંજૂરી મળી ગઈ છે. કોમન એરિયા લાઇટિંગ અને લિફ્ટ હવે 65% સૌર ઊર્જા પર ચાલશે, જેનાથી સોસાયટીના વીજળી બિલમાં દર મહિને આશરે ₹42,000 ની બચત થશે.",
      },
    },
  },
];

// 2 AGM entries with realistic details
export const INITIAL_MEETINGS: MeetingRecord[] = [
  {
    id: "meeting-agm-2026",
    title: "52nd Annual General Meeting (AGM) - 2026",
    date: "15 Aug 2026",
    time: "10:30 AM – 01:15 PM",
    venue: "Main Clubhouse & Virtual Webex Link",
    agenda: [
      "Review & adoption of audited financial statements for FY 2025-26",
      "Award of contract for exterior structural waterproofing & painting",
      "Sanctioning of 8 dedicated EV charging points across Basement 1",
      "Appointment of Statutory Auditor for FY 2026-27",
    ],
    attendeeCount: 74,
    minutesContent: `The 52nd AGM was convened on 15 Aug 2026 with 74 members present. Chairman Mr. Suresh Mehta presided.
1. Audited financials for FY 2025-26 showing net society surplus of ₹8.4 Lakhs were approved unanimously.
2. Technical evaluation of 3 waterproofing vendors was presented. Contract awarded to Asian Paints Project Services for ₹34.5 Lakhs from Sinking Fund with no special levy on residents.
3. Proposal to install 8 Tata Power smart EV chargers in Basement 1 approved on revenue-share model.
4. M/s S.R. Patki & Associates reappointed as Statutory Auditor.`,
    aiSummary: {
      overview: "52nd AGM attended by 74 members approved FY25-26 accounts with ₹8.4L surplus, sanctioned building exterior waterproofing without additional levy, and authorized 8 new EV charging bays.",
      keyDecisions: [
        "Unanimously passed audited financial accounts for FY 2025-26 with ₹8.4L surplus.",
        "Awarded ₹34.5L exterior waterproofing contract to Asian Paints funded through Sinking Fund.",
        "Approved 8 new EV charging points in Basement 1 on revenue-share terms.",
      ],
      actionItems: [
        { task: "Execute contract agreement with Asian Paints", assignee: "Secretary Rajesh Shetty", deadline: "31 Aug 2026" },
        { task: "Coordinate DISCOM net-metering for EV chargers", assignee: "Facilities Sub-committee", deadline: "15 Sep 2026" },
      ],
    },
    translations: {
      hi: {
        overview: "52वीं वार्षिक आम बैठक में 74 सदस्यों ने भाग लिया। वित्त वर्ष 25-26 के खातों, बिना किसी अतिरिक्त शुल्क के बाहरी रंग-रोगन, और 8 नए ईवी चार्जिंग पॉइंट को मंजूरी दी गई।",
        keyDecisions: [
          "₹8.4 लाख के अधिशेष के साथ ऑडिट किए गए वित्तीय खाते स्वीकृत।",
          "सिंकिंग फंड से ₹34.5 लाख का वॉटरप्रूफिंग व पेंटिंग कार्य स्वीकृत।",
          "बेसमेंट 1 में 8 ईवी चार्जर्स की स्थापना का निर्णय।",
        ],
      },
      mr: {
        overview: "५२व्या वार्षिक सर्वसाधारण सभेत इमारतीचे वॉटरप्रूफिंग व रंगकाम, इलेक्ट्रिक वाहन चार्जिंग आणि लेखापरीक्षित हिशेब मंजूर करण्यात आले.",
        keyDecisions: [
          "८.४ लाख रुपयांच्या नफ्यासह आर्थिक हिशेब एकमुखाने मंजूर.",
          "सिंकिंग फंडातून ३४.५ लाख रुपयांचे रंगकामाचे कंत्राट मंजूर; सभासदांवर कोणताही अतिरिक्त भार नाही.",
          "बेसमेंट १ मध्ये ८ नवीन ई-वाहन चार्जिंग पॉइंट्स बसवण्याचा ठराव संमत.",
        ],
      },
    },
  },
  {
    id: "meeting-agm-2025",
    title: "51st Annual General Meeting (AGM) - 2025",
    date: "17 Aug 2025",
    time: "10:00 AM – 12:45 PM",
    venue: "Main Clubhouse",
    agenda: [
      "Review & adoption of audited balance sheet for FY 2024-25",
      "Renewal of comprehensive AMC for OTIS elevators across Wings A, B, and C",
      "Security enhancement: installation of biometric RFID boom barriers & 32 HD IP CCTV cameras",
      "Approval of revised parking bye-laws and visitor vehicle clamping fee",
    ],
    attendeeCount: 68,
    minutesContent: `The 51st AGM of Emerald Heights CHS was held on 17 Aug 2025 with 68 flat owners in attendance.
1. Financial statements for FY 2024-25 were adopted with zero audit qualifications.
2. Managing Committee authorized to enter into a 3-year comprehensive AMC with OTIS Elevators at ₹4.8 Lakhs/year including full parts replacement.
3. Security automation project sanctioned at ₹6.2 Lakhs for RFID tag gate barriers and 32 full-HD CCTV cameras with 60-day recording retention.
4. Revised parking rule with ₹500 clamping penalty for unauthorized parking ratified.`,
    aiSummary: {
      overview: "51st AGM approved FY24-25 balance sheet, renewed a 3-year comprehensive AMC with OTIS Elevators, and authorized RFID gate barrier and 32 HD CCTV security automation.",
      keyDecisions: [
        "Adopted audited balance sheet for FY 2024-25 without objections.",
        "Approved 3-year OTIS elevator comprehensive maintenance contract at ₹4.8L/year.",
        "Sanctioned ₹6.2L for RFID boom barriers and 32 HD IP CCTV cameras at all gates.",
      ],
      actionItems: [
        { task: "Sign 3-year agreement with OTIS Elevator India", assignee: "Secretary Rajesh Shetty", deadline: "31 Aug 2025" },
        { task: "Complete CCTV installation and resident RFID issuance", assignee: "Security Committee", deadline: "30 Sep 2025" },
      ],
    },
  },
];

// 3 Festival drives: Anant Chaturdashi, Navratri, Diwali (Ganesh Utsav retired)
// Relational integrity: all donors are real seeded residents, slotsFilled matches count, sum matches collectedAmount
export const INITIAL_SPONSORSHIPS: SponsorshipCampaign[] = [
  {
    id: "camp-anant-2026",
    title: "Anant Chaturdashi Immersion & Visarjan Procession",
    description: "Eco-friendly immersion ceremony at the society artificial water tank, traditional Dhol-Tasha troop performance, evening community Prasad distribution, and flower shower procession across central society podium.",
    festivalDate: "28 Sep 2026",
    targetAmount: 75000,
    collectedAmount: 35000,
    bannerImage: "https://images.unsplash.com/photo-1567653418876-5bb0e566e1c2?w=800&auto=format&fit=crop&q=80",
    tiers: [
      {
        name: "Grand Procession Patron (Gold)",
        amount: 15000,
        perks: "VIP front-row seating + Special family Maha-Aarti slot + Family name on central festival banner",
        slotsAvailable: 2,
        slotsFilled: 1,
      },
      {
        name: "Dhol Tasha & Brass Band Supporter (Silver)",
        amount: 5000,
        perks: "Special recognition during procession + 5 family prasad boxes + Stage felicitation",
        slotsAvailable: 6,
        slotsFilled: 4,
      },
      {
        name: "Eco-Visarjan Tank & Flower Sponsor (Bronze)",
        amount: 2000,
        perks: "Name listed in festival souvenir booklet + Floral offering dedicated in family name",
        slotsAvailable: 15,
        slotsFilled: 0,
      },
    ],
    donations: [
      { id: "don-ac-1", donorName: "Vikram Malhotra", flatNumber: "C-303", amount: 15000, tierName: "Grand Procession Patron (Gold)", donatedAt: "22 Sep 2026" },
      { id: "don-ac-2", donorName: "Rajesh Shetty", flatNumber: "B-402", amount: 5000, tierName: "Dhol Tasha & Brass Band Supporter (Silver)", donatedAt: "23 Sep 2026" },
      { id: "don-ac-3", donorName: "Pooja Sharma", flatNumber: "A-101", amount: 5000, tierName: "Dhol Tasha & Brass Band Supporter (Silver)", donatedAt: "24 Sep 2026" },
      { id: "don-ac-4", donorName: "Ananya Iyer", flatNumber: "B-204", amount: 5000, tierName: "Dhol Tasha & Brass Band Supporter (Silver)", donatedAt: "25 Sep 2026" },
      { id: "don-ac-5", donorName: "Sunita Deshmukh", flatNumber: "C-102", amount: 5000, tierName: "Dhol Tasha & Brass Band Supporter (Silver)", donatedAt: "25 Sep 2026" },
    ],
  },
  {
    id: "camp-navratri-2026",
    title: "Navratri Dandiya & Garba Mahotsav 2026",
    description: "9 nights of vibrant Garba and Dandiya Raas in the society central amphitheater! Live traditional orchestra, professional sound & beam lighting, authentic Gujarati Farsan stalls, daily best-dressed prizes, and grand Vijayadashami celebration.",
    festivalDate: "11 Oct – 19 Oct 2026",
    targetAmount: 180000,
    collectedAmount: 64000,
    bannerImage: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&auto=format&fit=crop&q=80",
    tiers: [
      {
        name: "Title Sponsor - Garba Night Stage (Gold)",
        amount: 20000,
        perks: "Dedicated stage banner with family name + Guest of Honor for lighting opening deepak + 10 complimentary Dandiya stick sets",
        slotsAvailable: 4,
        slotsFilled: 2,
      },
      {
        name: "Traditional Orchestra & DJ Sponsor (Silver)",
        amount: 8000,
        perks: "Stage announcement on 3 nights + VIP seating reservation + Special Prasad hamper",
        slotsAvailable: 8,
        slotsFilled: 3,
      },
      {
        name: "Dandiya Sticks & Refreshments Patron (Bronze)",
        amount: 3000,
        perks: "Family name displayed at beverage & prasad counter + Participation memento",
        slotsAvailable: 15,
        slotsFilled: 0,
      },
    ],
    donations: [
      { id: "don-nav-1", donorName: "Pooja Sharma", flatNumber: "A-101", amount: 20000, tierName: "Title Sponsor - Garba Night Stage (Gold)", donatedAt: "01 Oct 2026" },
      { id: "don-nav-2", donorName: "Sunita Deshmukh", flatNumber: "C-102", amount: 20000, tierName: "Title Sponsor - Garba Night Stage (Gold)", donatedAt: "02 Oct 2026" },
      { id: "don-nav-3", donorName: "Rajesh Shetty", flatNumber: "B-402", amount: 8000, tierName: "Traditional Orchestra & DJ Sponsor (Silver)", donatedAt: "03 Oct 2026" },
      { id: "don-nav-4", donorName: "Ananya Iyer", flatNumber: "B-204", amount: 8000, tierName: "Traditional Orchestra & DJ Sponsor (Silver)", donatedAt: "04 Oct 2026" },
      { id: "don-nav-5", donorName: "Vikram Malhotra", flatNumber: "C-303", amount: 8000, tierName: "Traditional Orchestra & DJ Sponsor (Silver)", donatedAt: "05 Oct 2026" },
    ],
  },
  {
    id: "camp-diwali-2026",
    title: "Diwali Deepotsav & Community Illumination 2026",
    description: "Annual society facade fairy lighting, traditional diya lighting across all building corridors, musical sitar performance in the central amphitheater, and festive bonus hampers distribution for all 24 housekeeping and security guards.",
    festivalDate: "31 Oct – 02 Nov 2026",
    targetAmount: 120000,
    collectedAmount: 28000,
    bannerImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    tiers: [
      {
        name: "Security & Staff Gift Sponsor (Gold)",
        amount: 8000,
        perks: "Directly sponsor festive bonus hampers and sweets for 12 security & sanitation personnel + Felicitation plaque",
        slotsAvailable: 10,
        slotsFilled: 2,
      },
      {
        name: "Society Facade & Garden Illumination (Silver)",
        amount: 4000,
        perks: "Sponsor LED fairy illumination for building entrance arch & main garden gazebos",
        slotsAvailable: 12,
        slotsFilled: 3,
      },
      {
        name: "Diya & Rangoli Celebration Contributor (Bronze)",
        amount: 2000,
        perks: "Sponsor earthen diyas and eco-friendly rangoli colors for podium corridors",
        slotsAvailable: 20,
        slotsFilled: 0,
      },
    ],
    donations: [
      { id: "don-diw-1", donorName: "Rajesh Shetty", flatNumber: "B-402", amount: 8000, tierName: "Security & Staff Gift Sponsor (Gold)", donatedAt: "01 Oct 2026" },
      { id: "don-diw-2", donorName: "Ananya Iyer", flatNumber: "B-204", amount: 8000, tierName: "Security & Staff Gift Sponsor (Gold)", donatedAt: "02 Oct 2026" },
      { id: "don-diw-3", donorName: "Pooja Sharma", flatNumber: "A-101", amount: 4000, tierName: "Society Facade & Garden Illumination (Silver)", donatedAt: "03 Oct 2026" },
      { id: "don-diw-4", donorName: "Vikram Malhotra", flatNumber: "C-303", amount: 4000, tierName: "Society Facade & Garden Illumination (Silver)", donatedAt: "04 Oct 2026" },
      { id: "don-diw-5", donorName: "Sunita Deshmukh", flatNumber: "C-102", amount: 4000, tierName: "Society Facade & Garden Illumination (Silver)", donatedAt: "05 Oct 2026" },
    ],
  },
];

// Document requests: clean relational records
// Includes active pending (A-101), unavailable with 30-day message (B-402), and fulfilled (C-303)
export const INITIAL_DOCUMENT_REQUESTS: DocumentRequest[] = [
  {
    id: "req-1",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    deliveryEmail: "pooja.sharma@outlook.com",
    documentType: "noc_sale_rent",
    documentName: "NOC for Bank Loan / Mortgage Refinance",
    copyType: "digital",
    status: "pending",
    requestedAt: "10 Oct 2026, 11:30 AM",
    note: "Submitted to SBI Home Loans for interest rate re-assessment",
  },
  {
    id: "req-2",
    flatId: "flat-b402",
    flatNumber: "B-402",
    residentName: "Rajesh Shetty",
    deliveryEmail: "rajesh.shetty@emeraldheights.org",
    documentType: "share_certificate",
    documentName: "Society Share Certificate Duplicate Copy",
    copyType: "physical",
    status: "unavailable",
    requestedAt: "12 Oct 2026, 02:45 PM",
    note: "Required for property re-assessment and family succession ledger",
    notAvailableReason: DEFAULT_UNAVAILABLE_DOC_MESSAGE,
  },
  {
    id: "req-3",
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    deliveryEmail: "vikram.m@investments.in",
    documentType: "renovation_permission",
    documentName: "Renovation & Balcony Enclosure Permission",
    copyType: "digital",
    status: "fulfilled",
    requestedAt: "08 Oct 2026, 03:20 PM",
    fulfilledAt: "09 Oct 2026, 05:00 PM",
    fulfilledFileName: "Renovation_Permission_C303_Approved.pdf",
    note: "Interior painting and safety grill replacement",
  },
];

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: "comp-1",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    category: "water_supply",
    categoryLabel: "Water Supply",
    description: "Low water pressure in master bathroom flush line since Sunday morning.",
    status: "in_progress",
    createdAt: "13 Oct 2026, 08:30 AM",
    updatedAt: "13 Oct 2026, 02:00 PM",
    adminResponse: "Society plumber Mr. Ramu assigned. Inspection scheduled for today 3:00 PM.",
  },
  {
    id: "comp-2",
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    category: "lift_electrical",
    categoryLabel: "Lift / Electrical",
    description: "Building C lift sensor door occasionally gets stuck on Floor 3.",
    status: "pending",
    createdAt: "14 Oct 2026, 09:20 AM",
  },
  {
    id: "comp-3",
    flatId: "flat-b204",
    flatNumber: "B-204",
    residentName: "Ananya Iyer",
    category: "cleanliness",
    categoryLabel: "Cleanliness & Sanitation",
    description: "Garbage chute door on 2nd floor Building B requires latch repair and sanitization.",
    status: "resolved",
    createdAt: "09 Oct 2026, 04:00 PM",
    updatedAt: "11 Oct 2026, 11:30 AM",
    adminResponse: "Latch repaired and chute pressure-cleaned by housekeeping vendor.",
  },
];

// Clean facility bookings linked to real flats
export const INITIAL_FACILITY_BOOKINGS: FacilityBooking[] = [
  {
    id: "book-1",
    flatId: "flat-b204",
    flatNumber: "B-204",
    residentName: "Ananya Iyer",
    facility: "Clubhouse",
    date: "2026-10-25",
    timeSlot: "Evening (04:00 PM - 09:00 PM)",
    purpose: "Family Birthday Celebration & Dinner",
    status: "approved",
    createdAt: "12 Oct 2026, 11:30 AM",
    approvedAt: "13 Oct 2026, 05:00 PM",
    adminNotes: "Approved. Deposit ₹2,000 received by Treasurer.",
  },
  {
    id: "book-2",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    facility: "Society Ground",
    date: "2026-11-01",
    timeSlot: "Morning (09:00 AM - 01:00 PM)",
    purpose: "Wing A Youth Friendly Badminton Tournament",
    status: "pending",
    createdAt: "14 Oct 2026, 02:15 PM",
  },
  {
    id: "book-3",
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    facility: "Party Hall",
    date: "2026-11-08",
    timeSlot: "Full Day (09:00 AM - 10:00 PM)",
    purpose: "Diwali Family Gathering & Pooja",
    status: "approved",
    createdAt: "10 Oct 2026, 09:40 AM",
    approvedAt: "11 Oct 2026, 03:00 PM",
    adminNotes: "Approved. Music volume to adhere to quiet hours after 10 PM.",
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [];
