import {
  FlatUser,
  MaintenanceBill,
  DocumentItem,
  SocietyRule,
  Notice,
  MeetingRecord,
  SponsorshipCampaign,
  DocumentRequest,
  ComplaintTicket,
  FacilityBooking,
  Notification,
} from "../types";

// 4 Residents across Building A, B, C + Admin
export const INITIAL_FLATS: FlatUser[] = [
  // Admin
  {
    id: "flat-admin",
    flatNumber: "MC-Office",
    wing: "Society Office",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Managing Committee (Secretary - Rajesh Shetty)",
    email: "committee@emeraldheights.org",
    phone: "+91 22 2640 9988",
    role: "admin",
    isOwner: true,
    possessionDate: "01 Jan 2015",
    parkingSlot: "Admin Reserved (P-01)",
    pin: "1234",
  },

  // Building A
  {
    id: "flat-a101",
    flatNumber: "A-101",
    wing: "Building A",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Pooja Sharma",
    email: "pooja.sharma@outlook.com",
    phone: "+91 98450 11223",
    role: "resident",
    isOwner: true,
    possessionDate: "05 Jan 2019",
    parkingSlot: "P-04 (Covered Ground)",
    pin: "1234",
  },

  // Building B
  {
    id: "flat-b402",
    flatNumber: "B-402",
    wing: "Building B",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Rajesh Shetty",
    email: "rajesh.shetty@emeraldheights.org",
    phone: "+91 98200 44201",
    role: "resident",
    isOwner: true,
    possessionDate: "10 Mar 2018",
    parkingSlot: "P-42 (Covered Ground)",
    pin: "1234",
  },
  {
    id: "flat-b204",
    flatNumber: "B-204",
    wing: "Building B",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Ananya Iyer",
    email: "ananya.iyer@fintech.in",
    phone: "+91 98208 22208",
    role: "resident",
    isOwner: true,
    possessionDate: "01 Dec 2018",
    parkingSlot: "P-49 (Basement 2)",
    pin: "1234",
  },

  // Building C
  {
    id: "flat-c303",
    flatNumber: "C-303",
    wing: "Building C",
    buildingName: "Emerald Heights CHS Ltd.",
    residentName: "Vikram Malhotra",
    email: "vikram.m@investments.in",
    phone: "+91 98210 33311",
    role: "resident",
    isOwner: true,
    possessionDate: "01 Nov 2020",
    parkingSlot: "P-70 (Basement 2)",
    pin: "1234",
  },
];

export const INITIAL_BILLS: MaintenanceBill[] = [
  {
    id: "bill-2026-10-a101",
    flatId: "flat-a101",
    flatNumber: "A-101",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-04)", amount: 500, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 1400, category: "property_tax" },
    ],
    totalAmount: 6200,
    status: "pending",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 1400,
  },
  {
    id: "bill-2026-09-a101",
    flatId: "flat-a101",
    flatNumber: "A-101",
    monthYear: "September 2026",
    billingDate: "01 Sep 2026",
    dueDate: "15 Sep 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-04)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "paid",
    paidAt: "10 Sep 2026, 04:32 PM",
    paymentRef: "UPI/260910482910/HDFC",
    paymentMethod: "UPI",
    isPropertyTaxIncluded: false,
  },
  {
    id: "bill-2026-08-a101",
    flatId: "flat-a101",
    flatNumber: "A-101",
    monthYear: "August 2026",
    billingDate: "01 Aug 2026",
    dueDate: "15 Aug 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-04)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "paid",
    paidAt: "08 Aug 2026, 11:15 AM",
    paymentRef: "UPI/260808912384/ICICI",
    paymentMethod: "UPI",
    isPropertyTaxIncluded: false,
  },
  {
    id: "bill-2026-10-b402",
    flatId: "flat-b402",
    flatNumber: "B-402",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Covered Ground Parking (P-42)", amount: 500, category: "parking" },
      { id: "i5", name: "Annual Municipal Property Tax (Pro-rata)", amount: 1400, category: "property_tax" },
    ],
    totalAmount: 6200,
    status: "paid",
    paidAt: "04 Oct 2026, 10:20 AM",
    paymentRef: "UPI/261004128912/KOTAK",
    paymentMethod: "UPI",
    isPropertyTaxIncluded: true,
    propertyTaxAmount: 1400,
  },
  {
    id: "bill-2026-10-b204",
    flatId: "flat-b204",
    flatNumber: "B-204",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Basement Parking (P-49)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "pending",
    isPropertyTaxIncluded: false,
  },
  {
    id: "bill-2026-10-c303",
    flatId: "flat-c303",
    flatNumber: "C-303",
    monthYear: "October 2026",
    billingDate: "01 Oct 2026",
    dueDate: "15 Oct 2026",
    items: [
      { id: "i1", name: "Society Maintenance & Security Fee", amount: 3200, category: "maintenance" },
      { id: "i2", name: "Sinking & Major Repair Fund", amount: 650, category: "sinking_fund" },
      { id: "i3", name: "Water & Common Utility Charges", amount: 450, category: "water" },
      { id: "i4", name: "Basement Parking (P-70)", amount: 500, category: "parking" },
    ],
    totalAmount: 4800,
    status: "pending",
    isPropertyTaxIncluded: false,
  }
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: "doc-1",
    flatId: "flat-b402",
    title: "Registered Agreement for Sale (Flat B-402)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_b402.pdf",
    fileSize: "4.2 MB",
    fileType: "pdf",
    uploadedAt: "15 Mar 2018",
    uploadedBy: "Secretary (Emerald Heights)",
  },
  {
    id: "doc-2",
    flatId: "flat-b402",
    title: "Society Share Certificate (Certificate No. 042)",
    category: "share_certificate",
    fileUrl: "https://example.com/docs/share_cert_b402.pdf",
    fileSize: "1.8 MB",
    fileType: "pdf",
    uploadedAt: "20 May 2018",
    uploadedBy: "Treasurer (Emerald Heights)",
  },
  {
    id: "doc-3",
    flatId: "flat-b402",
    title: "Bank Loan Clearance & Society NOC",
    category: "noc",
    fileUrl: "https://example.com/docs/bank_noc_b402.pdf",
    fileSize: "850 KB",
    fileType: "pdf",
    uploadedAt: "10 Feb 2022",
    uploadedBy: "Secretary (Emerald Heights)",
  },
  {
    id: "doc-4",
    flatId: "flat-b402",
    title: "EV Charger Installation Permission & Electrical Load NOC",
    category: "noc",
    fileUrl: "https://example.com/docs/ev_charger_noc_b402.pdf",
    fileSize: "620 KB",
    fileType: "pdf",
    uploadedAt: "14 Jul 2025",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-5",
    flatId: "flat-a101",
    title: "Registered Agreement for Sale (Flat A-101)",
    category: "agreement",
    fileUrl: "https://example.com/docs/sale_deed_a101.pdf",
    fileSize: "3.9 MB",
    fileType: "pdf",
    uploadedAt: "12 Jan 2019",
    uploadedBy: "Secretary",
  },
  {
    id: "doc-6",
    isSocietyWide: true,
    title: "Model Bye-laws of Maharashtra Co-op Housing Societies (2014 Edition)",
    category: "bylaws",
    fileUrl: "https://example.com/docs/society_byelaws_master.pdf",
    fileSize: "6.5 MB",
    fileType: "pdf",
    uploadedAt: "01 Jan 2023",
    uploadedBy: "Managing Committee",
  },
  {
    id: "doc-7",
    isSocietyWide: true,
    title: "Annual Fire Safety & Lift Audit Certificate (Form B 2026)",
    category: "insurance",
    fileUrl: "https://example.com/docs/fire_safety_audit_2026.pdf",
    fileSize: "2.1 MB",
    fileType: "pdf",
    uploadedAt: "18 Jun 2026",
    uploadedBy: "MC Facilities Head",
  },
];

export const INITIAL_RULES: SocietyRule[] = [
  {
    id: "rule-1",
    title: "Visitor & EV Vehicle Parking Regulations",
    category: "parking",
    description: "Visitors are permitted to park in designated yellow-bay visitor slots for a maximum of 6 consecutive hours. Overnight visitor parking requires prior security intimation via SMS/app. EV charging at designated slots must be freed within 30 minutes of 100% charge completion.",
    penaltyInfo: "₹500 wheel-clamp fee for unauthorized parking in private resident slots.",
    originMeeting: "AGM 2024 (Minute 7.2 - 14 Aug 2024)",
    effectiveDate: "01 Sep 2024",
    lastUpdated: "12 Mar 2025",
    version: 2,
  },
  {
    id: "rule-2",
    title: "Flat Interior Renovation & Drilling Hours",
    category: "renovation",
    description: "Civil work, heavy carpentry, and power drilling are strictly restricted to 10:00 AM – 1:00 PM and 3:00 PM – 6:00 PM on Mondays through Saturdays. No loud work is allowed on Sundays or declared public holidays. Debris must be cleared via service elevator only.",
    penaltyInfo: "₹2,000 fine on owner + immediate cessation of contractor entry.",
    originMeeting: "EGM on Resident Harmony (18 Nov 2023)",
    effectiveDate: "01 Dec 2023",
    lastUpdated: "01 Dec 2023",
    version: 1,
  },
  {
    id: "rule-3",
    title: "Pet Care & Leash Mandate in Common Areas",
    category: "pets",
    description: "All companion dogs must be on a leash when traversing corridors, lobbies, and elevators. Pet owners must utilize Elevator #2 (service lift) during peak morning rush (8:00 AM – 9:30 AM). Owners are legally responsible for scooping waste on society lawns/jogging tracks.",
    penaltyInfo: "₹1,000 fine for repeated littering in common areas.",
    originMeeting: "AGM 2023 (Minute 4.1 - 20 Aug 2023)",
    effectiveDate: "01 Sep 2023",
    lastUpdated: "15 Apr 2024",
    version: 3,
  },
  {
    id: "rule-4",
    title: "Quiet Hours & Terrace Party Guidelines",
    category: "noise",
    description: "Strict quiet hours apply across all wings between 10:30 PM and 7:00 AM. Terrace bookings for private gatherings are allowed up to 10:00 PM with zero amplified sound after 10:00 PM as per municipal noise pollution norms. Max 40 guests allowed per booking.",
    penaltyInfo: "Forfeiture of ₹5,000 security deposit for noise violations after 10:30 PM.",
    originMeeting: "EGM (09 Feb 2024)",
    effectiveDate: "01 Mar 2024",
    lastUpdated: "01 Mar 2024",
    version: 1,
  },
  {
    id: "rule-5",
    title: "Mandatory 3-Way Waste Segregation",
    category: "waste_management",
    description: "Household waste must be handed to housekeeping staff strictly segregated into Green (Wet/Biodegradable), Blue (Dry/Recyclable), and Red (Hazardous/Sanitary) bins at doorstep collection between 7:30 AM and 9:00 AM. Unsegregated bags will not be picked up.",
    penaltyInfo: "₹250 refusal notice per occurrence.",
    originMeeting: "Swachh Society Drive Resolution (10 Jan 2025)",
    effectiveDate: "01 Feb 2025",
    lastUpdated: "01 Feb 2025",
    version: 1,
  },
  {
    id: "rule-6",
    title: "Clubhouse Gymnasium & Swimming Pool Etiquette",
    category: "clubhouse",
    description: "Gymnasium is open 6:00 AM – 11:00 AM and 5:00 PM – 10:00 PM. Appropriate sportswear and clean footwear mandatory. Swimming pool requires nylon swimwear and mandatory pre-shower. Children under 12 must be accompanied by an adult.",
    originMeeting: "AGM 2022 (07 Aug 2022)",
    effectiveDate: "15 Aug 2022",
    lastUpdated: "10 Jun 2025",
    version: 2,
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: "notice-1",
    title: "Overhead Water Tank Cleaning & Supply Interruption (Tomorrow)",
    content: "Please be informed that semi-annual cleaning and sanitization of the overhead water tanks for Wings A, B, and C will take place tomorrow, Thursday, from 10:00 AM to 02:00 PM. Water supply will be suspended during this window. Residents are kindly advised to store adequate water for morning/afternoon usage.",
    body: "Please be informed that semi-annual cleaning and sanitization of the overhead water tanks for Wings A, B, and C will take place tomorrow, Thursday, from 10:00 AM to 02:00 PM. Water supply will be suspended during this window. Residents are kindly advised to store adequate water for morning/afternoon usage.",
    category: "urgent",
    postedAt: "02 Oct 2026, 06:15 PM",
    postedBy: "Facilities & Maintenance Sub-Committee",
    isPinned: true,
    translations: {
      hi: {
        title: "पानी की आपूर्ति में रुकावट — कल",
        content: "टैंक की निर्धारित सफाई और रखरखाव के लिए कल सुबह 10:00 बजे से दोपहर 2:00 बजे तक पानी की आपूर्ति बाधित रहेगी। कृपया पहले से पानी जमा कर लें। असुविधा के लिए हमें खेद है।",
        body: "टैंक की निर्धारित सफाई और रखरखाव के लिए कल सुबह 10:00 बजे से दोपहर 2:00 बजे तक पानी की आपूर्ति बाधित रहेगी। कृपया पहले से पानी जमा कर लें। असुविधा के लिए हमें खेद है।",
      },
      mr: {
        title: "पाणी पुरवठा खंडित — उद्या",
        content: "टाकीची नियोजित स्वच्छता आणि देखभालीसाठी उद्या सकाळी १०:०० ते दुपारी २:०० वाजेपर्यंत पाणीपुरवठा बंद राहील. कृपया पाण्याचा साठा अगोदर करून ठेवा. गैरसोयीबद्दल आम्ही दिलगीर आहोत.",
        body: "टाकीची नियोजित स्वच्छता आणि देखभालीसाठी उद्या सकाळी १०:०० ते दुपारी २:०० वाजेपर्यंत पाणीपुरवठा बंद राहील. कृपया पाण्याचा साठा अगोदर करून ठेवा. गैरसोयीबद्दल आम्ही दिलगीर आहोत.",
      },
      gu: {
        title: "પાણી પુરવઠો બંધ રહેશે — આવતીકાલે",
        content: "ટાંકીની નિયમિત સફાઈ અને સમારકામ માટે આવતીકાલે સવારે ૧૦:૦૦ થી બપોરે ૨:૦૦ વાગ્યા સુધી પાણી પુરવઠો બંધ રહેશે. કૃપા કરીને અગાઉથી પાણીનો સંગ્રહ કરી લો. અગવડતા બદલ અમે દિલગીર છીએ.",
        body: "ટાંકીની નિયમિત સફાઈ અને સમારકામ માટે આવતીકાલે સવારે ૧૦:૦૦ થી બપોરે ૨:૦૦ વાગ્યા સુધી પાણી પુરવઠો બંધ રહેશે. કૃપા કરીને અગાઉથી પાણીનો સંગ્રહ કરી લો. અગવડતા બદલ અમે દિલગીર છીએ.",
      },
    },
  },
  {
    id: "notice-2",
    title: "Rooftop Solar Grid Net-Metering Commissioning Completed",
    content: "The Managing Committee is delighted to share that the 45kW rooftop solar photovoltaic system has received final grid synchronization approval from Tata Power / MSEDCL. Common area lighting and elevator power will now run 65% on renewable solar energy, resulting in projected monthly savings of ₹42,000 on common electricity bills.",
    body: "The Managing Committee is delighted to share that the 45kW rooftop solar photovoltaic system has received final grid synchronization approval from Tata Power / MSEDCL. Common area lighting and elevator power will now run 65% on renewable solar energy, resulting in projected monthly savings of ₹42,000 on common electricity bills.",
    category: "maintenance",
    postedAt: "28 Sep 2026, 11:00 AM",
    postedBy: "Managing Committee",
    isPinned: false,
    translations: {
      hi: {
        title: "रूफटॉप सोलर ग्रिड कमीशनिंग सफलतापूर्वक संपन्न",
        content: "प्रबंध समिति को यह बताते हुए हर्ष हो रहा है कि हमारे 45kW रूफटॉप सोलर सिस्टम को ग्रिड से जोड़ दिया गया है। कॉमन एरिया की लाइटिंग और लिफ्ट अब 65% सौर ऊर्जा से संचालित होंगी, जिससे सोसाइटी के बिजली बिल में प्रतिमाह लगभग ₹42,000 की बचत होगी।",
        body: "प्रबंध समिति को यह बताते हुए हर्ष हो रहा है कि हमारे 45kW रूफटॉप सोलर सिस्टम को ग्रिड से जोड़ दिया गया है। कॉमन एरिया की लाइटिंग और लिफ्ट अब 65% सौर ऊर्जा से संचालित होंगी, जिससे सोसाइटी के बिजली बिल में प्रतिमाह लगभग ₹42,000 की बचत होगी।",
      },
      mr: {
        title: "छतावरील सोलर ग्रीडचे काम पूर्ण झाले",
        content: "व्यवस्थापन समितीला हे सांगताना आनंद होत आहे की ४५ किलोवॅट क्षमतेच्या सोलर पॅनेल प्रणालीला मंजुरी मिळाली आहे. सामान्य भागातील दिवे आणि लिफ्ट आता सौर ऊर्जेवर चालतील, ज्यामुळे दरमहा साधारण ₹४२,००० विजेच्या बिलात बचत होईल.",
        body: "व्यवस्थापन समितीला हे सांगताना आनंद होत आहे की ४५ किलोवॅट क्षमतेच्या सोलर पॅनेल प्रणालीला मंजुरी मिळाली आहे. सामान्य भागातील दिवे आणि लिफ्ट आता सौर ऊर्जेवर चालतील, ज्यामुळे दरमहा साधारण ₹४२,००० विजेच्या बिलात बचत होईल.",
      },
      gu: {
        title: "રૂફટોપ સોલર ગ્રીડ કમિશનિંગ સફળતાપૂર્વક પૂર્ણ થયું",
        content: "મેનેજિંગ કમિટી જણાવતા ખુશી અનુભવે છે કે આપણી 45kW રૂફટોપ સોલાર સિસ્ટમને ટાટા પાવર / MSEDCL દ્વારા અંતિમ મંજૂરી મળી ગઈ છે. કોમન એરિયા લાઇટિંગ અને લિફ્ટ હવે 65% સૌર ઊર્જા પર ચાલશે, જેનાથી સોસાયટીના વીજળી બિલમાં દર મહિને આશરે ₹42,000 ની બચત થશે.",
        body: "મેનેજિંગ કમિટી જણાવતા ખુશી અનુભવે છે કે આપણી 45kW રૂફટોપ સોલાર સિસ્ટમને ટાટા પાવર / MSEDCL દ્વારા અંતિમ મંજૂરી મળી ગઈ છે. કોમન એરિયા લાઇટિંગ અને લિફ્ટ હવે 65% સૌર ઊર્જા પર ચાલશે, જેનાથી સોસાયટીના વીજળી બિલમાં દર મહિને આશરે ₹42,000 ની બચત થશે.",
      },
    },
  },
  {
    id: "notice-3",
    title: "Festive Season Security & Courier Parcel Locker Guidelines",
    content: "With the festive parcel surge, all courier deliveries will be held at the Smart Delivery Kiosk located near the main security gate. Guards will scan packages and residents will receive an OTP for instant self-pickup. Valuables/food deliveries may still proceed directly to flat doors.",
    body: "With the festive parcel surge, all courier deliveries will be held at the Smart Delivery Kiosk located near the main security gate. Guards will scan packages and residents will receive an OTP for instant self-pickup. Valuables/food deliveries may still proceed directly to flat doors.",
    category: "general",
    postedAt: "20 Sep 2026, 04:30 PM",
    postedBy: "Security Sub-Committee",
    isPinned: false,
    translations: {
      hi: {
        title: "त्योहारी सीजन सुरक्षा एवं कूरियर पार्सल लॉकर दिशानिर्देश",
        content: "त्योहारी मौसम में पार्सल की अधिक संख्या को देखते हुए सभी कूरियर डिलीवरी मुख्य सुरक्षा गेट के पास स्थित स्मार्ट डिलीवरी कियोस्क पर रखी जाएंगी। गार्ड पैकेज स्कैन करेंगे और सदस्यों को स्वयं पिकअप के लिए ओटीपी मिलेगा। मूल्यवान वस्तुएं और भोजन डिलीवरी सीधे फ्लैट के दरवाजे तक आ सकती हैं।",
        body: "त्योहारी मौसम में पार्सल की अधिक संख्या को देखते हुए सभी कूरियर डिलीवरी मुख्य सुरक्षा गेट के पास स्थित स्मार्ट डिलीवरी कियोस्क पर रखी जाएंगी। गार्ड पैकेज स्कैन करेंगे और सदस्यों को स्वयं पिकअप के लिए ओटीपी मिलेगा। मूल्यवान वस्तुएं और भोजन डिलीवरी सीधे फ्लैट के दरवाजे तक आ सकती हैं।",
      },
      mr: {
        title: "सणासुदीच्या काळातील सुरक्षा आणि कुरिअर पार्सल नियमावली",
        content: "सणासुदीच्या काळात वाढत्या पार्सल डिलिव्हरीच्या पार्श्वभूमीवर सर्व कुरिअर पार्सल मुख्य प्रवेशद्वाराजवळील स्मार्ट डिलिव्हरी कियोस्कवर ठेवले जातील. सुरक्षा रक्षक पॅकेट स्कॅन करतील आणि सदस्यांना ओटीपी पाठवला जाईल. जेवणाची आणि मौल्यवान डिलिव्हरी थेट फ्लॅटपर्यंत जाऊ शकते.",
        body: "सणासुदीच्या काळात वाढत्या पार्सल डिलिव्हरीच्या पार्श्वभूमीवर सर्व कुरिअर पार्सल मुख्य प्रवेशद्वाराजवळील स्मार्ट डिलिव्हरी कियोस्कवर ठेवले जातील. सुरक्षा रक्षक पॅकेट स्कॅन करतील आणि सदस्यांना ओटीपी पाठवला जाईल. जेवणाची आणि मौल्यवान डिलिव्हरी थेट फ्लॅटपर्यंत जाऊ शकते.",
      },
      gu: {
        title: "તહેવારોની સિઝનમાં સુરક્ષા અને કુરિયર પાર્સલ લોકર માર્ગદર્શિકા",
        content: "તહેવારોની સિઝનમાં પાર્સલના ધસારાને ધ્યાનમાં રાખીને, તમામ કુરિયર ડિલિવરી મુખ્ય સુરક્ષા ગેટ પાસેના સ્માર્ટ ડિલિવરી કિઓસ્ક પર રાખવામાં આવશે. ગાર્ડ પેકેજ સ્કેન કરશે અને સભ્યોને સેલ્ફ-પિકઅપ માટે ઓટીપી પ્રાપ્ત થશે. કિંમતી સામાન અને ફૂડ ડિલિવરી સીધા ફ્લેટના દરવાજા સુધી જઈ શકે છે.",
        body: "તહેવારોની સિઝનમાં પાર્સલના ધસારાને ધ્યાનમાં રાખીને, તમામ કુરિયર ડિલિવરી મુખ્ય સુરક્ષા ગેટ પાસેના સ્માર્ટ ડિલિવરી કિઓસ્ક પર રાખવામાં આવશે. ગાર્ડ પેકેજ સ્કેન કરશે અને સભ્યોને સેલ્ફ-પિકઅપ માટે ઓટીપી પ્રાપ્ત થશે. કિંમતી સામાન અને ફૂડ ડિલિવરી સીધા ફ્લેટના દરવાજા સુધી જઈ શકે છે.",
      },
    },
  },
];

export const INITIAL_MEETINGS: MeetingRecord[] = [
  {
    id: "meeting-52-agm",
    title: "52nd Annual General Meeting (AGM 2026)",
    date: "23 Aug 2026",
    time: "10:30 AM – 01:45 PM",
    venue: "Clubhouse Banquet Hall & Hybrid Zoom",
    agenda: [
      "Review and approval of Audited Financial Accounts FY 2025-26",
      "Sanction of Sinking Fund allocation for exterior waterproofing & repainting",
      "Installation of EV Charging Infrastructure in Basement Parking",
      "Appointment of Statutory Auditors for FY 2026-27",
    ],
    attendeeCount: 74,
    minutesContent: `The 52nd Annual General Body Meeting commenced under the chairmanship of Mr. K. V. Narayanan. 
1. Financial Accounts: The Treasurer presented the audited balance sheet showing a surplus of ₹8.4 Lakhs in the general fund. The accounts were passed unanimously.
2. Building Repainting & Waterproofing: After evaluating three civil engineering tenders, the body voted (62 in favor, 12 against) to award the contract to M/s Asian Structurals for ₹34.5 Lakhs, funded via existing sinking fund reserves with no extra resident special levy. Work to commence in November 2026.
3. EV Charging: Proposal to install 8 centralized 7.4kW AC Type-2 chargers in Basement 1 approved on a user-pay per kWh model via prepaid RFID card.
4. Auditor: M/s S. P. Joshi & Associates re-appointed as Statutory Auditor.`,
    aiSummary: {
      overview: "The 52nd AGM achieved a 74-member quorum. Crucial approvals passed for FY25-26 balance sheet, external structural repainting without extra levies, and centralized EV charging points.",
      keyDecisions: [
        "Approved audited FY25-26 accounts with ₹8.4L operational surplus.",
        "Awarded ₹34.5L exterior waterproofing/painting contract to M/s Asian Structurals, funded 100% via Sinking Fund reserves.",
        "Approved 8 centralized EV smart chargers in Basement 1 on prepaid RFID model.",
        "Re-appointed M/s S.P. Joshi & Associates as statutory auditor.",
      ],
      actionItems: [
        { task: "Sign contract and finalize scaffolding safety schedule with Asian Structurals", assignee: "Secretary & Works Committee", deadline: "15 Oct 2026" },
        { task: "Deploy EV charging cabling & RFID billing console", assignee: "Facilities Manager", deadline: "30 Nov 2026" },
        { task: "File audited AGM returns with District Co-operative Registrar", assignee: "Treasurer", deadline: "30 Sep 2026" },
      ],
    },
    translations: {
      hi: {
        overview: "52वीं वार्षिक आम बैठक में 74 सदस्यों ने भाग लिया। वित्त वर्ष 25-26 के खातों, बिना किसी अतिरिक्त शुल्क के बाहरी रंग-रोगन, और 8 नए ईवी चार्जिंग पॉइंट को मंजूरी दी गई।",
        keyDecisions: [
          "₹8.4 लाख के अधिशेष के साथ ऑडिट किए गए वित्तीय खाते स्वीकृत।",
          "सिंकिंग फंड से ₹34.5 लाख का वॉटरप्रूफिंग व पेंटिंग कार्य स्वीकृत।",
          "बेसमेंट 1 में 8 ईवी चार्जर्स की स्थापना का निर्णय।",
        ],
      },
      mr: {
        overview: "५२व्या वार्षिक सर्वसाधारण सभेत इमारतीचे वॉटरप्रूफिंग व रंगकाम, इलेक्ट्रिक वाहन चार्जिंग आणि लेखापरीक्षित हिशेब मंजूर करण्यात आले.",
        keyDecisions: [
          "८.४ लाख रुपयांच्या नफ्यासह आर्थिक हिशेब एकमुखाने मंजूर.",
          "सिंकिंग फंडातून ३४.५ लाख रुपयांचे रंगकामाचे कंत्राट मंजूर; सभासदांवर कोणताही अतिरिक्त भार नाही.",
          "बेसमेंट १ मध्ये ८ नवीन ई-वाहन चार्जिंग पॉइंट्स बसवण्याचा ठराव संमत.",
        ],
      },
    },
  },
  {
    id: "meeting-egm-solar",
    title: "Extraordinary General Meeting (EGM) - Solar Project",
    date: "14 Apr 2026",
    time: "06:00 PM – 07:30 PM",
    venue: "Clubhouse 1st Floor",
    agenda: [
      "Evaluation of Rooftop Solar Grid Proposal (45 kW capacity)",
      "Subsidy processing under PM Surya Ghar Muft Bijli Yojana",
    ],
    attendeeCount: 58,
    minutesContent: `EGM called specifically for the solar energy transition project. The Energy Sub-committee presented technical bids from 4 empaneled vendors. Tata Power Solar proposal of ₹24 Lakhs with 40% central subsidy was approved unanimously. Expected ROI period is 3.2 years.`,
    aiSummary: {
      overview: "EGM unanimously approved the 45kW rooftop solar project with Tata Power Solar, leveraging central solar subsidies for an expected 3.2-year payback.",
      keyDecisions: [
        "Approved 45kW solar PV grid installation with Tata Power Solar.",
        "Authorized committee to apply for government subsidy and DISCOM net-metering.",
      ],
      actionItems: [
        { task: "Submit DISCOM load feasibility documentation", assignee: "Energy Sub-committee", deadline: "30 Apr 2026" },
      ],
    },
  },
];

export const INITIAL_SPONSORSHIPS: SponsorshipCampaign[] = [
  {
    id: "camp-ganesh-2026",
    title: "Ganesh Utsav & Grand Cultural Mela 2026",
    description: "Join us in celebrating our 14th Eco-Friendly Ganesh Utsav! 5 days of cultural performances, traditional Modak distribution, kids drawing competitions, musical evening, and community Maha-Prasad lunch.",
    festivalDate: "18 – 22 Sep 2026",
    targetAmount: 250000,
    collectedAmount: 187500,
    bannerImage: "https://images.unsplash.com/photo-1567653418876-5bb0e566e1c2?w=800&auto=format&fit=crop&q=80",
    tiers: [
      {
        name: "Grand Festival Patron (Gold)",
        amount: 25000,
        perks: "VIP front-row seating for all 5 nights + Special family Maha-Aarti slot + Banner recognition at stage",
        slotsAvailable: 5,
        slotsFilled: 3,
      },
      {
        name: "Maha-Prasad Sponsor (Silver)",
        amount: 10000,
        perks: "Co-host of Community Feast + Name displayed during Maha-Prasad + 10 special prasad boxes",
        slotsAvailable: 10,
        slotsFilled: 7,
      },
      {
        name: "Aarti & Decoration Supporter (Bronze)",
        amount: 5000,
        perks: "Evening Aarti dedicated in your family's name + Floral decoration sponsorship plaque",
        slotsAvailable: 20,
        slotsFilled: 14,
      },
    ],
    donations: [
      { id: "d1", donorName: "Rajesh & Meena Shetty", flatNumber: "B-402", amount: 10000, tierName: "Maha-Prasad Sponsor (Silver)", message: "Wishing all society members a blessed Ganesh Utsav! Ganpati Bappa Morya!", donatedAt: "10 Sep 2026" },
      { id: "d2", donorName: "Dr. Arvind Kulkarni", flatNumber: "A-504", amount: 25000, tierName: "Grand Festival Patron (Gold)", message: "For children's cultural prizes and stage audio.", donatedAt: "08 Sep 2026" },
      { id: "d3", donorName: "Sunita Deshmukh", flatNumber: "C-102", amount: 5000, tierName: "Aarti & Decoration Supporter (Bronze)", message: "In memory of late Shri S. R. Deshmukh.", donatedAt: "12 Sep 2026" },
      { id: "d4", donorName: "Pooja Sharma", flatNumber: "A-101", amount: 5000, tierName: "Aarti & Decoration Supporter (Bronze)", message: "Excited for the Dandiya and music night!", donatedAt: "14 Sep 2026" },
      { id: "d5", donorName: "Amitabh Banerjee", flatNumber: "B-203", amount: 2500, message: "General contribution for Eco-friendly immersion.", donatedAt: "15 Sep 2026" },
    ],
  },
  {
    id: "camp-diwali-2026",
    title: "Diwali Deepotsav & Community Rangoli Evening",
    description: "Annual society facade fairy lighting, traditional diya lighting across all building corridors, musical sitar performance in the central amphitheater, and sweets box distribution for all housekeeping & security staff.",
    festivalDate: "31 Oct – 02 Nov 2026",
    targetAmount: 120000,
    collectedAmount: 48000,
    tiers: [
      {
        name: "Security & Staff Gift Sponsor",
        amount: 8000,
        perks: "Sponsor festive bonus hampers for 12 security & sanitation guards",
        slotsAvailable: 10,
        slotsFilled: 4,
      },
      {
        name: "Illumination Patron",
        amount: 3500,
        perks: "Sponsor entrance arch lighting and solar lanterns",
        slotsAvailable: 15,
        slotsFilled: 5,
      },
    ],
    donations: [
      { id: "dd1", donorName: "Siddharth Jain", flatNumber: "A-601", amount: 8000, tierName: "Security & Staff Gift Sponsor", message: "Gratitude to our hardworking security team.", donatedAt: "01 Oct 2026" },
      { id: "dd2", donorName: "Rajesh Shetty", flatNumber: "B-402", amount: 3500, tierName: "Illumination Patron", message: "Happy Diwali in advance to all neighbors!", donatedAt: "02 Oct 2026" },
    ],
  },
];

export const INITIAL_DOCUMENT_REQUESTS: DocumentRequest[] = [
  {
    id: "req-1",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    deliveryEmail: "pooja.sharma@emeraldheights.in",
    documentType: "noc_sale_rent",
    documentName: "NOC for Bank Loan / Mortgage",
    copyType: "digital",
    status: "fulfilled",
    requestedAt: "10 Oct 2026, 11:30 AM",
    fulfilledAt: "11 Oct 2026, 04:15 PM",
    fulfilledFileName: "NOC_BankLoan_A101_Signed.pdf",
    note: "Submitted to SBI Home Loans",
  },
  {
    id: "req-2",
    flatId: "flat-b402",
    flatNumber: "B-402",
    residentName: "Rajesh Shetty",
    deliveryEmail: "rajesh.shetty@emeraldheights.org",
    documentType: "share_certificate",
    documentName: "Society Share Certificate Copy",
    copyType: "physical",
    status: "pending",
    requestedAt: "12 Oct 2026, 02:45 PM",
    note: "Required for property re-assessment",
  },
  {
    id: "req-3",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    deliveryEmail: "pooja.sharma@emeraldheights.in",
    documentType: "renovation_permission",
    documentName: "Renovation & Balcony Enclosure Form",
    copyType: "digital",
    status: "pending",
    requestedAt: "14 Oct 2026, 10:15 AM",
    note: "Interior painting and dry balcony waterproofing",
  },
];

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: "comp-1",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    category: "water_supply",
    categoryLabel: "Water Supply",
    description: "Low pressure in master bathroom flush line since Sunday morning.",
    status: "in_progress",
    createdAt: "13 Oct 2026, 08:30 AM",
    updatedAt: "13 Oct 2026, 02:00 PM",
    adminResponse: "Society plumber Mr. Ramu assigned. Inspection booked for today 3 PM.",
  },
  {
    id: "comp-2",
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    category: "lift_electrical",
    categoryLabel: "Lift / Electrical",
    description: "Building C lift sensor door occasionally gets stuck on Floor 3.",
    status: "pending",
    createdAt: "14 Oct 2026, 09:20 AM",
  },
  {
    id: "comp-3",
    flatId: "flat-b204",
    flatNumber: "B-204",
    residentName: "Ananya Iyer",
    category: "cleanliness",
    categoryLabel: "Cleanliness & Sanitation",
    description: "Garbage chute door on 2nd floor Building B requires latch repair and sanitization.",
    status: "resolved",
    createdAt: "09 Oct 2026, 04:00 PM",
    updatedAt: "11 Oct 2026, 11:30 AM",
    adminResponse: "Latch repaired and chute pressure-cleaned by housekeeping vendor.",
  },
];

export const INITIAL_FACILITY_BOOKINGS: FacilityBooking[] = [
  {
    id: "book-1",
    flatId: "flat-a101",
    flatNumber: "A-101",
    residentName: "Pooja Sharma",
    facility: "Clubhouse",
    date: "2026-10-25",
    timeSlot: "Evening (04:00 PM - 09:00 PM)",
    purpose: "Family Birthday Celebration & Dinner",
    status: "approved",
    createdAt: "12 Oct 2026, 11:30 AM",
    approvedAt: "13 Oct 2026, 05:00 PM",
    adminNotes: "Approved. Deposit ₹2,000 received by Treasurer.",
  },
  {
    id: "book-2",
    flatId: "flat-c303",
    flatNumber: "C-303",
    residentName: "Vikram Malhotra",
    facility: "Society Ground",
    date: "2026-11-01",
    timeSlot: "Morning (09:00 AM - 01:00 PM)",
    purpose: "Wing C Youth Friendly Cricket Match",
    status: "pending",
    createdAt: "14 Oct 2026, 02:15 PM",
  },
  {
    id: "book-3",
    flatId: "flat-b204",
    flatNumber: "B-204",
    residentName: "Ananya Iyer",
    facility: "Party Hall",
    date: "2026-11-08",
    timeSlot: "Full Day (09:00 AM - 10:00 PM)",
    purpose: "Diwali Family Pooja & Bhajan Gathering",
    status: "approved",
    createdAt: "10 Oct 2026, 09:40 AM",
    approvedAt: "11 Oct 2026, 03:00 PM",
    adminNotes: "Approved. Music volume to adhere to quiet hours after 10 PM.",
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [];
